Fix a crash with opkg-convert when xsltproc is not installed.
git-svn-id: http://svn.oscar.openclustergroup.org/oscar/pkgsrc@6162 18f9d06c-6ae2-0310-8438-938a554feff9

diff --git a/src/opkg-convert b/src/opkg-convert
--- a/src/opkg-convert
+++ b/src/opkg-convert
@@ -238,6 +238,10 @@ function convert_config_xml() {
     newconfig=$olddir/config.xml.new
 
     xsltproc=`check_tool xsltproc`
+    if [ ! -n "$xsltproc" ]; then
+        echo "ERROR: XSLT tool not found (executing \"check_tool xsltproc\")"
+        exit 1
+    fi
 
     write_convert_stylesheet
     echo "[CONVERT] config.xml"
